### ISSUE TITLE
[libpng18] spurious autoconf files

### ISSUE THREAD

**Issue by jbowler** [pnggroup/libpng#591]
scripts/autoconf remains even though the rest of the autoconf files have been deleted, this causes really weird behavior.

**Comment by ctruta** [comment]
Ha! This: https://github.com/pnggroup/libpng/blob/00343a761e41e56acaeb0517aec5325d3b951837/autogen.sh#L84
So I missed them.

**Comment by ctruta** [comment]
Fixed.

**Comment by ctruta** [comment]
... and I missed your commit ff3f84f3f5e6527384e786137d7eb7dceddae33e, which does this also.
In any case, I'll send an announcement to png-mng-implement, and I'll start picking up commits.

**Comment by jbowler** [comment]
> I'll start picking up commits.

Yeah; I layered the autoconf fix on all the other changes since I needed it to continue testing.  I just revalidated the use-ISO-... fix so the now rebased #575, #589, #590 sequence are good to go.  I've tested on Intel SSE and AArch64 (before the pngvalid/pngstest breaks).

I still don't know exactly how they got broken; I'm pretty sure I can find it but I don't want to do that if you are going to remove all the libpng 1.7 #ifs en masse.
